
image: Visual Studio 2017
install:
  - choco install dotnetcore
  - .paket\paket.bootstrapper.exe
build_script:
  - build.cmd -t build
test_script:
  - cmd: build.cmd -t test_only
branches:
  only:
    - master
